### ISSUE TITLE
Fenster "Teilnehmer bearbeiten"

### ISSUE THREAD

**Issue by sonne001** [dschweie/TournamentManager#21]
Fenster auf ursprüngliche Größe verändern.

**Comment by dschweie** [comment]
Grund für das geänderte Fenster ist ein .pack(), dass für Linux eingefügt wurde.

Dialog muss auch unter Linux gut zu sehen sein.

**Comment by sonne001** [comment]
Verstehe ich nicht.- Fenster war ursprünglich größer und sollte wieder größer werden

**Comment by dschweie** [comment]
wurde mit Commit ff0ce4f gefixt
