### ISSUE TITLE
Anlegen einer neuen Runde, ohne die Regeln zu verletzen

### ISSUE THREAD

**Issue by sonne001** [dschweie/TournamentManager#38]
Auch wenn die Bemerkung „**Es kann keine weitere Runde angelegt werden, ohne die Regeln zu verletzen**“ sollte eine weitere Auslosung erfolgen!

**Comment by dschweie** [comment]
Es stellt sich die Frage, wie das möglich sein soll?

Grundsätzlich lassen sich keine Runden anlegen, wenn weniger als 4 Spieler oder genau  7 Spieler in dem laufenden Turnier aktiv sind.

Was ich mir vorstellen kann, ist eine manuelle Erfassung von Spielpaarungen. Das wäre eine zusätzliche Anforderung, die sich auch aus #36 ableiten lässt, da dort auch die manuelle Vergabe von Plätzen gefordert wird.

**Comment by sonne001** [comment]
Ich habe mit 15 Teilnehmern getestet. Nach der 3. Runde bekam ich die Fehlermeldung.

**Comment by sonne001** [comment]
Hallo Dirk,

 

Deine Antwort habe ich nicht verstanden. Was heißt neue Runde „Mischen“?- 

 

In unserem Reglement steht zu Auslosung:

Bei der Auslosung der Paarungen wird lediglich darauf geachtet, dass ein Team nicht zweimal in gleicher Besetzung spielt. Sollte durch die Anzahl der Teilnehmer keine reine Doublette-Auslosung möglich sein, wird entweder zusätzlich ein Triplette oder ein „Unechtes“ gespielt (letzte Paarung der Auslosung), es gibt kein Freilos. 

Das heißt, wir haben ein Luxus-Problem.- Daher mein Vorschlag
Es erscheint der Hinweis, wie bisher
Es wird eine neue Runde, unter Verletzung der Regeln, ausgelost.
Nun kann der Turnierleiter über die weitere Vorgehenswiese entscheiden. 

 

Mit freundlichen Grüßen

Dieter Friedrich

 

 

Von: dschweie <notifications@github.com>
Antworten an: dschweie/TournamentManager <reply@reply.github.com>
Datum: Freitag, 2. November 2018 um 19:37
An: dschweie/TournamentManager <TournamentManager@noreply.github.com>
Cc: sonne001 <df2016@gmx.de>, Assign <assign@noreply.github.com>
Betreff: Re: [dschweie/TournamentManager] Anlegen einer neuen Runde, ohne die Regeln zu verletzen (#38)

 

Entscheidung zu diesem Ticket: Es wird über das Menü die Möglichkeit geben, dass man eine Runde "Mischen" kann. Das bedeutet, dass die noch aktiven Spieler gemischt werden und dann in das Feld eingefügt werden.

Zusätzlich wurde für manuelle Erfassung von Spielpaarungen #39 erfasst.

**Comment by dschweie** [comment]
Hallo Dieter, 

ganz richtig, ich denke auch, dass wir ein Luxusproblem haben.

Wenn 15 Spieler im Turnier die erste Runde gespielt haben, dann haben in der ersten Runde 9 Spieler Triplette gespielt. Damit können keine 9 Spieler gefunden werden, die ins Triplette gesetzt werden können.

Ein Spieler, der im Triplette war hat in der ersten Runde bereits mit/gegen 5 von 14 Teilnehmern gespielt. Wenn er dann nochmal ins Triplette kommt, ist er bereits 10 von 14 Teilnehmern begegnet. Damit muss er in dritten Runde mindestens im unechten Triplette spielen und ist dann allen 14 Teilnehmern begegnet.

Ein Spieler, der im Triplette war hatte nach der ersten Runde zwei Mitspieler. Wenn der in der zweiten Runde wieder Triplette spielt, dann werden zwei Mitspieler gesucht, die noch nicht miteinander gespielt haben. Nach der dritten Runde hat jeder Spieler mit 3 bis 6 unterschiedlichen Spielern gespielt. Wenn es jetzt um die 4 Runde geht, dann kann es unmöglich sein, dass zu einem Spieler im Triplette zwei Spieler gefunden werden, die noch nicht miteinander gespielt haben.

Mit Mischen meine ich, dass alle Spieler in eine Liste kommen, die dann gemischt wird und dann werden die Plätze einfach besetzt. Damit lassen sich dann beliebige Runden spielen.

Viele Grüße
Dirk

**Comment by dschweie** [comment]
Das Ticket wurde geschlossen, da auf Basis der Diskussion und der bereits vorhandenen Erweiterungen bezüglich der Regeln kein Handlungsbedarf zu erkennen ist.
