### ISSUE TITLE
Teilnehmer erfassen

### ISSUE THREAD

**Issue by sonne001** [dschweie/TournamentManager#41]
In der Regel soll die Erfassung der Teilnehmer schnell erfolgen. Aus diesem Grunde wäre es Vorteilhaft, wenn folgende Reihenfolge vorgesehen ist
1.	Name (hier kann Nachname + Vorname, nur Nachname oder Cosename wie „Shugar“ reingeschrieben werden.
2.	Optional-Felder
    a.	      Verein
    b.       E-Mail-Adresse.
Ich denke, ein weiteres Feld wie Vorname ist schön, aber nicht notwendig.
Wenn aber Vorname und Nachname vorgesehen, dann in Reihenfolge 
	Nachname dann Vorname.

**Comment by dschweie** [comment]
Ich habe den Vornamen bewusst aufgenommen, um später die Suche zu vereinfachen. Ein Spieler kann dann über die Einstellungen Vorname oder Nachname oder Verein bzw. eine Kombination gesucht werden.

Zusätzliche Eingaben möchte ich eher in einer "Teilnehmerverwaltung" sehen. Dort kann dann zu allen Teilnehmern nahezu beliebige Informationen verwaltet werden. Ich kann mir auch vorstellen, dass man dort Mails mit den Turnierankündigungen erstellen und verschicken kann. Dazu kann man den Teilnehmern dann auch Verteiler zuordnen, so dass man z.B. für Groß-Gerau und Klein-Gerau eigene Verteiler pflegen kann.

Wenn das auf Zustimmung trifft, dann bitte Ticket schließen oder Stellungnahme als Kommentar ergänzen.

**Comment by sonne001** [comment]
Die Praxis sagt etwas Anderes.- In der Regel kommen kurz vor Anmeldeschluss die Teilnehmer (TN) zur Anmeldung. Dann soll es schnell gehen, da alle auf die Auslosung und Spielbeginn warten. Jede zusätzliche Betätigung der Tastatur (z.B.: Tab-Taste usw.) kostet Zeit.

Daher mein Vorschlag, folgende Felder in dieser Reihenfolge:
	1. TeilnehmerName, Verein, E-Mail oder 
		Hier kann der Turnierleiter entscheiden, ob Name und Vorname (in TeilnehmerName) eingegeben werden soll.
	2. Name; Vorname; Verein; E-Mail

In beiden Fällen kann man mit wenigen Klicks einen neuen TN aufnehmen.

**Comment by sonne001** [comment]
Einverstanden.- Aber dann bitte zuerst Nachname und dann Vorname….

 

Mit freundlichen Grüßen

Dieter Friedrich

 

 

Von: dschweie <notifications@github.com>
Antworten an: dschweie/TournamentManager <reply@reply.github.com>
Datum: Freitag, 9. November 2018 um 17:27
An: dschweie/TournamentManager <TournamentManager@noreply.github.com>
Cc: sonne001 <df2016@gmx.de>, Assign <assign@noreply.github.com>
Betreff: Re: [dschweie/TournamentManager] Teilnehmer erfassen (#41)

 

Jede zusätzliche Betätigung der Tastatur (z.B.: Tab-Taste usw.) kostet Zeit.

Das sehe ich auch so. Aus diesem Grund wird in dem Dialog keine Mailadresse zu finden sein und ich möchte, dass der Turnierleiter über den Vornamen oder den Nachnamen Vorschläge bekommt, welcher Spieler "mit einem Klick" einzusetzen ist.

Das könnte dann so aussehen:

Wenn die Software eine ordentliche Verwaltung der Mitglieder bekommen soll, dann werde ich Vor- und Nachname auch speichern. Die Variante mit Spitznamen widerspricht dem Konzept nicht, da aktuell keines der Felder ein Pflichtfeld ist.

**Comment by dschweie** [comment]
@sonne001 : Ticket wurde geschlossen, da es sich aus meiner Sicht erledigt hat. Wenn nicht, bitte ein Ticket für den offenen Teil erstellen.
