### ISSUE TITLE
Button „ok + weiterer Teilnehmer“

### ISSUE THREAD

**Issue by sonne001** [dschweie/TournamentManager#42]
2 Auffälligkeiten:
    **1.**	 Nachdem ich einen Teilnehmer erfasst habe, drücke ich mit der Maus „ok + weiterer Teilnehmer“.        Es erscheint ein neues Fenster „Teilnehmer erfassen“, jedoch ist das Feld „Nachname“ noch mit dem vorherigen Eintrag gefüllt.
**2.**	In der Maske „Teilnehmer erfassen“ fülle ich die entsprechenden Felder aus, gehe mit der Tab-Taste auf „OK + weiterer Teilnehmer“ und drücke die Eingabe-Taste.
a.	Teilnehmer wird aufgenommen	
b.	Jedoch öffnet sich nicht die Maske „Teilnehmer erfassen“.

**Comment by dschweie** [comment]
Die Schaltfläche Übernehmen ist weiterhin die, für die ENTER oder RETURN definiert ist.
Mit Leertaste wir weitere Eingabe ermöglicht.
