### ISSUE TITLE
Dialog „Supermeleé

### ISSUE THREAD

**Issue by sonne001** [dschweie/TournamentManager#45]
Da wird augenblicklich nichts von den Auswahlmöglichkeiten angezeigt.- Ganz gleich welche Auswahl ich treffe.

**Comment by dschweie** [comment]
Ja, ist aktuell ein Dummy, bis auf den Menüpunkt
Supermêlée
 > Runde erstellen > Teilnehmer manuell setzen
Der Dialog kann auf Look and Feel geprüft werden, die Eingaben werden aktuell nicht übernommen.
