### ISSUE TITLE
Nummernvergabe ist nicht korrekt

### ISSUE THREAD

**Issue by bigbottich** [dschweie/TournamentManager#55]
Nummern werden doppelt vergeben, wenn zwischendurch, d.h. bei der Eingabe neuer TN, TN gelöscht werden.
![grafik](https://user-images.githubusercontent.com/45695223/49661592-be79a580-fa49-11e8-843f-f11e6599d1fa.png)

**Comment by dschweie** [comment]
Hallo @bigbottich,

bitte mal genau beschreiben, wie sich dieses Phänomen reproduzieren lässt. Aus dem Screenshot geht leider nicht hervor, welche Version der Software genutzt wurde.

Aktuell ist das Release 0.0.5a-preview.

Viele Grüße
Dirk

**Comment by bigbottich** [comment]
Hmm, bekomme ich mit 5a auch nicht mehr hin.

**Comment by dschweie** [comment]
Okay, wird somit erstmal geschlossen.

**Comment by dschweie** [comment]
Fehler ist reproduizert:
Wenn man einen Spieler bearbeitet und dann die Bearbeitung abbricht, wird fälschlicher Weise der Index um den Wert 1 reduziert!
