### ISSUE TITLE
Vormane wird in TN-Liste nicht angezeigt

### ISSUE THREAD

**Issue by bigbottich** [dschweie/TournamentManager#57]
![grafik](https://user-images.githubusercontent.com/45695223/49661784-54153500-fa4a-11e8-82fc-a2bb234b32a0.png)

Vorname anzeigen.

**Comment by bigbottich** [comment]
> 
> 
> ![grafik](https://user-images.githubusercontent.com/45695223/49661784-54153500-fa4a-11e8-82fc-a2bb234b32a0.png)
> 
> Vorname anzeigen.

**Comment by bigbottich** [comment]
Hallo Dirk,
Vorname ist ein eigenes Eingabefeld, daher sollte es auch in einer extra Spalte angezeigt werden.
Gerade, wenn Du nach Namen suchen willst, wird es bei vielen Teilnehmern unübersichtlich.
=> Daraus folgt auch, dass je Spalte sortiert werden können sollte. Hilft auch beim Suchen.

Viele Grüße
Klaus

**Comment by bigbottich** [comment]
Hallo Dirk,
Vorname ist ein eigenes Eingabefeld, daher sollte es auch in einer extra Spalte angezeigt werden.
Gerade, wenn Du nach Namen suchen willst, wird es bei vielen Teilnehmern unübersichtlich.
=> Daraus folgt auch, dass je Spalte sortiert werden können sollte. Hilft auch beim Suchen.

Viele Grüße
Klaus

**Comment by dschweie** [comment]
Kleiner Aufwand und wird daher umgesetzt.
