### ISSUE TITLE
Reiter Rangliste

### ISSUE THREAD

**Issue by sonne001** [dschweie/TournamentManager#65]
1. Für eine Tagesauswertung wird die Spalte "Punkte" nicht benötigt.
2. Besser, nach jeder Runde eine Spalte "Differenz Runde x" und eine Spalte "Differenz Gesamt". 
3. Obwohl noch keine Runde gespielt wurde, haben alle TN schon 3 Punkte.
4. Nach weiteren Runden ist die Punktvergabe unklar und nicht korrekt.
![noch keine runde gespielt](https://user-images.githubusercontent.com/44161277/50784308-97fb9400-12ad-11e9-8851-a0816470cd9c.JPG)
![punkte nach 1 runde](https://user-images.githubusercontent.com/44161277/50784328-a9dd3700-12ad-11e9-80cd-6c414a0bf831.JPG)

**Comment by dschweie** [comment]
Wiedereröffnet

**Comment by dschweie** [comment]
@sonne001 : Bitte keine "Sammeltickets" schreiben. Hier werden Punkte angesprochen, die nicht zusammen gehören.

zu 4.: Ja, Fehler ist erkannt. Hier habe ich einen Denkfehler eingebaut und aus diesem Grund bekommen zu viele Teilnehmer die 3 Punkte für den Tagessieg.

zu 3.: Richtig, da alle angetreten sind, sind quasi alle "Tagessieger". Kann ich aber ändern.

zu 2.: Halte ich für nicht angebracht, da die Tabelle dann zu eng werden kann. Was man überlegen kann, ist eine gesonderte Sicht mit mehreren Spalten.
