### ISSUE TITLE
Zeiteinstellung

### ISSUE THREAD

**Issue by sonne001** [dschweie/TournamentManager#67]
1. Mit rechten und linken Mausklick lässt sich die Zeit nur reduzieren.
2. Nach Ablauf der Zeit wäre ein akustisches Signal von Vorteil

**Comment by dschweie** [comment]
@sonne001 : Habe mich falsch ausgedrückt. Wenn Du im linken  Bereich des Zeitbalken klickst, wird die Zeit reduziert. Ein Klick im rechten Bereich erhöht die Zeit. Einfach mal hinter der Angabe der Sekunden klicken.

Optional plane ich eine freie Eingabe über ein Kontextmenü.

**Comment by sonne001** [comment]
Funktioniert. Danke
