### ISSUE TITLE
Datenbank "Mongo"

### ISSUE THREAD

**Issue by sonne001** [dschweie/TournamentManager#77]
Die DB sollte zuerst den Nachnamen, dann den Vornamen anzeigen.

**Comment by dschweie** [comment]
Das wäre dann eine Rolle rückwärts in Bezug auf Ticket #47 . 

Wenn in dem Auswahlfeld der Nachname zuerst stehen soll, dann auch in dem Dialog.

Bitte bestätigen, dass es wieder geändert werden soll.

**Comment by dschweie** [comment]
Habe verstanden, um was es geht. IM Dialog steht der Nachname links und im Auswahlfeld der Vorname. Das ist nicht konsequent und wird geändert.

@sonne001 Sorry, sollte erst denken und dann tippen.
