### ISSUE TITLE
Teilnehmer Neuaufnahme

### ISSUE THREAD

**Issue by sonne001** [dschweie/TournamentManager#8]
> Button sollte in deutscher Sprache sein

> Fenster "Neu-Eingabe" -> Text in "Teilnehmer aufnehmen" ändern

> Wenn ich Fenster "Neu-Eingabe" aufrufe und anschließend auf abbrechen klicke und wieder aufrufe, zählt der Zähler immer weiter.- Besser Zähler zählt nicht hoch!

> Schnelleingabe ermöglichen.- Durch Return-Taste neues "Aufnahme-Fenster" öffnen. (im Augenblick nur durch Mausklick möglich).

> Im Augenblick weiß ich nicht für "Substitional" seht und für was es gebaucht werden könnte. (Deutsche Übersetzung wäre hilfreich)

**Comment by dschweie** [comment]
> > Schnelleingabe ermöglichen.- Durch Return-Taste neues "Aufnahme-Fenster" öffnen. (im Augenblick nur durch Mausklick möglich).

Die Anforderung wird in Ticket #13 weiterverfolgt.

**Comment by dschweie** [comment]
Es gibt mit  ff0ce4f einen Button, der die Eingabe weiterer Benutzer ermöglicht.
Übersetzungen sind noch anzupassen,
